### ISSUE TITLE
Fix AtlernateVersions Tabs in MovieDetails on Mobile

### ISSUE THREAD

**Issue by kbeelman** [kbeelman/TokuCinema#11]
Currently, if the screen width is less than what the AlternateVersions tabs allows, the tabs rollover onto a new line. This UI needs to be optimized for mobile browsers.

**Comment by kbeelman** [comment]
Potential Solution: Add arrows on the left and right of the tabs that allow the user to cycle through the AlternateVersions one at a time.

Potential Solution: Add arrows on the left and right of the tabs that allow the user to pan through the list, possibly similar to a carousel.

**Comment by bayes343** [comment]
I think I can take care of this one too.
