### ISSUE TITLE
Media page sort order

### ISSUE THREAD

**Issue by kbeelman** [kbeelman/TokuCinema#23]
Linking to the Media page (i.e., clicking the Media link from the Navigation) versus reloading the page results in the list of Media having a different sort order. Reloading the Media page seems to sort the Media in the order in which they are listed in Firebase.

Linking to the Media page (results in the desired sort order):
<img width="960" alt="media-gallery" src="https://i.imgur.com/PSQ0Pfb.png">

Linking to the Media page:
<img width="960" alt="media-gallery" src="https://i.imgur.com/ptr6fF1.png">

**Comment by bayes343** [comment]
@kbeelman, I don't remember what it's supposed to sort by.  Did you just want it to be by year?  So like, by year within each country section?

**Comment by kbeelman** [comment]
It should sort by the movie's release date, which it does correctly when you click on a link to that page. When you reload the page, it sorts the media in the order they appear in Firebase (but still separated by countries).

**Comment by bayes343** [comment]
Cool, it's sounds like a change detection thing.  A good use case for an Angular "Pipe."  Those things re-run whenever changes occur.

**Comment by kbeelman** [comment]
Thanks for fixing this, and thanks for thinking ahead and fixing this issue for movies as well. The movies in Firebase are basically already in the order that they show up in on the site, but it looks like this issue could have affected them as well. Good catch!
